#!/usr/bin/env python
"""
PowerRun Industries - build the blog at /blog/.

Each article is one file in scripts/blog_posts/<slug>.html: a JSON header in
an HTML comment, then the article body as plain HTML (h2, p, ul, table).

    <!--
    {
      "title": "Shown as the H1 and in blog cards",
      "seo_title": "Optional shorter <title> for Google (about 60 characters)",
      "description": "Meta description and card summary (under 160 characters)",
      "date": "2026-10-03",
      "updated": "optional, when the article was last revised",
      "topic": "Lithium Batteries",
      "related": ["lithium-batteries", "hybrid-inverters"]
    }
    -->
    <p>First paragraph...</p>

This script writes /blog/<slug>/index.html for every article and the
/blog/index.html listing, newest first. scripts/seo_build.py adds them to
sitemap.xml. To publish a new article: add the file, then

    python scripts/blog_build.py
    python scripts/stamp_assets.py

and commit. Needs no network access.
"""
import io
import json
import math
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import seo_build as b  # noqa: E402  (shared head block / escaping helpers)

ROOT = b.ROOT
POSTS = os.path.join(ROOT, "scripts", "blog_posts")
OUT = os.path.join(ROOT, "blog")
SITE_NAME = "PowerRun Industries"
CATEGORY_NAMES = {
    "hybrid-inverters": "Hybrid Inverters",
    "lithium-batteries": "Lithium Batteries",
    "solar-panels": "Solar Panels",
    "e-rickshaw-batteries": "E-Rickshaw Batteries",
}

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
{head}
<meta name="theme-color" content="#ff5a00">
<link rel="icon" href="/assets/powerrun-logo.png">
<link rel="preconnect" href="https://nnkopxkyxcmtiunftlgr.supabase.co" crossorigin>
<link rel="stylesheet" href="/assets/css/site.css">
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<div id="pr-header"></div>
<!-- Generated by scripts/blog_build.py from scripts/blog_posts/ - edit there. -->
<main id="main" data-blog>
{body}
</main>
<div id="pr-footer"></div>

<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.48.0/dist/umd/supabase.js"></script>
<script src="/assets/js/config.js"></script>
<script src="/assets/js/core.js"></script>
<script src="/assets/js/seo.js"></script>
<script src="/assets/js/cart.js"></script>
<script src="/assets/js/layout.js"></script>
<script src="/assets/js/pages/blog.js"></script>
</body>
</html>
"""


def site_context():
    """Site URL, Organization node and Search Console tag, taken from the home
    page that seo_build.py last wrote, so the blog needs no database access."""
    _, _, site = b.config()
    home = io.open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
    org = re.search(r'id="ld-organization">(.*?)</script>', home)
    gsc = re.search(r'name="google-site-verification" content="([^"]*)"', home)
    image = re.search(r'property="og:image" content="([^"]*)"', home)
    return (site, json.loads(org.group(1)) if org else None, gsc.group(1) if gsc else None,
            image.group(1) if image else site + "/assets/powerrun-logo.png")


def load_posts():
    posts = []
    for name in sorted(os.listdir(POSTS)):
        if not name.endswith(".html"):
            continue
        text = io.open(os.path.join(POSTS, name), encoding="utf-8").read()
        match = re.match(r"\s*<!--(.*?)-->\s*(.*)$", text, re.S)
        if not match:
            raise SystemExit("%s: missing the <!-- {json} --> header" % name)
        meta = json.loads(match.group(1))
        for key in ("title", "description", "date"):
            if not meta.get(key):
                raise SystemExit("%s: header needs %r" % (name, key))
        meta["slug"] = name[:-5]
        meta["body"] = match.group(2).strip()
        words = len(re.sub(r"<[^>]+>", " ", meta["body"]).split())
        meta["minutes"] = max(1, int(math.ceil(words / 200.0)))
        posts.append(meta)
    return sorted(posts, key=lambda p: (p["date"], p["slug"]), reverse=True)


def nice_date(iso):
    import datetime
    return datetime.date.fromisoformat(iso).strftime("%d %b %Y").lstrip("0")


def card(post):
    url = "/blog/%s/" % post["slug"]
    return ('<article class="blog-card"><a href="%s">'
            '<span class="blog-topic">%s</span><h3>%s</h3><p>%s</p>'
            '<span class="blog-meta">%s · %d min read</span></a></article>'
            % (url, b.esc(post.get("topic") or "Guide"), b.esc(post["title"]), b.esc(post["description"]),
               nice_date(post["date"]), post["minutes"]))


def write(rel, html, stamp):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, "w", encoding="utf-8").write(b.versioned(html, stamp))


def main():
    site, org, gsc, default_image = site_context()
    stamp = b.asset_stamp()
    posts = load_posts()
    blog_url = site + "/blog/"

    # ------------------------------------------------------------- articles
    for post in posts:
        url = blog_url + post["slug"] + "/"
        article = {
            "@context": "https://schema.org", "@type": "BlogPosting",
            "headline": post["title"], "description": post["description"],
            "datePublished": post["date"], "dateModified": post.get("updated") or post["date"],
            "mainEntityOfPage": url, "image": default_image,
            "author": {"@type": "Organization", "name": SITE_NAME, "url": site + "/"},
            "publisher": {"@type": "Organization", "name": SITE_NAME,
                          "logo": {"@type": "ImageObject", "url": site + "/assets/powerrun-logo.png"}},
        }
        crumbs = b.breadcrumb_schema([("Home", site + "/"), ("Blog", blog_url), (post["title"], url)])
        head = b.head_block(title=post.get("seo_title") or (post["title"] + " | PowerRun"),
                            description=post["description"], canonical=url, image=default_image,
                            site_name=SITE_NAME, og_type="article", gsc=gsc,
                            schema=[s for s in (org, crumbs) if s])
        head = head.replace(b.END, '<meta property="article:published_time" content="%s">\n'
                                   '<script type="application/ld+json" id="ld-article">%s</script>\n%s'
                            % (post["date"], json.dumps(article, ensure_ascii=False, separators=(",", ":")), b.END))
        related = [s for s in post.get("related", []) if s in CATEGORY_NAMES]
        others = [p for p in posts if p["slug"] != post["slug"]][:3]
        body = (
            '    <section class="page-head">\n'
            '      <nav class="breadcrumb" aria-label="Breadcrumb" style="color:#999"><a href="/">Home</a> / '
            '<a href="/blog/">Blog</a> / <span aria-current="page" style="color:#fff">%s</span></nav>\n'
            '      <h1>%s</h1>\n'
            '      <p class="blog-meta">%s · %d min read%s</p>\n'
            '    </section>\n'
            '    <section class="section">\n'
            '      <article class="blog-article prose">\n%s\n'
            '      </article>\n'
            '%s'
            '      <div class="panel category-cta blog-cta">\n'
            '        <h2>Need help choosing?</h2>\n'
            '        <p>Tell us your load, backup hours or vehicle model and our team will suggest the right product.</p>\n'
            '        <a class="btn orange" href="https://wa.me/918700307676" target="_blank" rel="noopener">CHAT ON WHATSAPP</a>\n'
            '        <a class="outline" href="tel:+918700307676">CALL +91 87003 07676</a>\n'
            '      </div>\n'
            '    </section>\n'
            '%s'
            % (b.esc(post["title"]), b.esc(post["title"]), nice_date(post["date"]), post["minutes"],
               (" · Updated " + nice_date(post["updated"])) if post.get("updated") else "",
               post["body"],
               ('      <div class="internal-links blog-shop"><b>Shop this guide</b><div class="link-chips">%s'
                '</div></div>\n' % "".join('<a href="/%s/">%s</a>' % (s, CATEGORY_NAMES[s]) for s in related))
               if related else "",
               ('    <section class="section" style="padding-top:0">\n'
                '      <div class="section-head"><h2>MORE <span>GUIDES</span></h2>'
                '<a class="view" href="/blog/">All guides →</a></div>\n'
                '      <div class="blog-grid">\n%s\n      </div>\n    </section>'
                % "\n".join("        " + card(p) for p in others)) if others else ""))
        write(os.path.join("blog", post["slug"], "index.html"), PAGE.format(head=head, body=body), stamp)
        print("article  /blog/%s/" % post["slug"])

    # -------------------------------------------------------------- listing
    listing = {
        "@context": "https://schema.org", "@type": "Blog", "name": "PowerRun Energy Guides", "url": blog_url,
        "blogPost": [{"@type": "BlogPosting", "headline": p["title"], "url": blog_url + p["slug"] + "/",
                      "datePublished": p["date"]} for p in posts],
    }
    head = b.head_block(title="Solar, Inverter & Battery Guides | PowerRun Blog",
                        description="Practical guides to sizing hybrid inverters, lithium batteries, solar panels "
                                    "and e-rickshaw batteries for Indian homes and businesses.",
                        canonical=blog_url, image=default_image, site_name=SITE_NAME, gsc=gsc,
                        schema=[s for s in (org, b.breadcrumb_schema([("Home", site + "/"), ("Blog", blog_url)])) if s])
    head = head.replace(b.END, '<script type="application/ld+json" id="ld-blog">%s</script>\n%s'
                        % (json.dumps(listing, ensure_ascii=False, separators=(",", ":")), b.END))
    body = ('    <section class="page-head">\n'
            '      <nav class="breadcrumb" aria-label="Breadcrumb" style="color:#999"><a href="/">Home</a> / '
            '<span aria-current="page" style="color:#fff">Blog</span></nav>\n'
            '      <h1>Energy Guides</h1>\n'
            '      <p>Straight answers on sizing inverters, batteries and solar panels - written by the PowerRun team.</p>\n'
            '    </section>\n'
            '    <section class="section">\n'
            '      <div class="blog-grid">\n%s\n      </div>\n'
            '    </section>' % "\n".join("        " + card(p) for p in posts))
    write(os.path.join("blog", "index.html"), PAGE.format(head=head, body=body), stamp)
    print("listing  /blog/  (%d articles)" % len(posts))
    print("\nNext: python scripts/stamp_assets.py, then commit and push.")


if __name__ == "__main__":
    sys.exit(main())
