-- ============================================================================
-- PowerRun Industries - Production schema migration (04 / catalogue seed)
--
-- IMPORTANT: these prices, MRPs and stock levels are PLACEHOLDERS derived from
-- the price list that was already hard-coded in the website's PR_SEED array.
-- Review and correct every one of them in Admin > Products before going live.
--
-- Matching is by SKU, so running this again simply refreshes the same 25 rows.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Sub-categories (children of the existing top-level categories)
-- ---------------------------------------------------------------------------
insert into public.categories (name, slug, description, parent_id, sort_order, is_active)
select v.name, v.slug, v.description, parent.id, v.sort_order, true
from (values
  ('Residential Hybrid Inverters','residential-hybrid-inverters','Hybrid inverters for homes and small offices','Hybrid Inverters',1),
  ('Commercial Hybrid Inverters','commercial-hybrid-inverters','Higher capacity hybrid inverters for commercial loads','Hybrid Inverters',2),
  ('24V LFP Batteries','24v-lfp-batteries','25.6V LiFePO4 battery packs','Lithium Batteries',1),
  ('48V LFP Batteries','48v-lfp-batteries','51.2V LiFePO4 battery packs','Lithium Batteries',2),
  ('Mono PERC Panels','mono-perc-panels','High efficiency mono PERC solar modules','Solar Panels',1),
  ('Bifacial Panels','bifacial-panels','Bifacial high output solar modules','Solar Panels',2),
  ('48V E-Rickshaw Batteries','48v-e-rickshaw-batteries','48V and 51.2V e-rickshaw packs','E-Rickshaw Batteries',1),
  ('72V E-Rickshaw Batteries','72v-e-rickshaw-batteries','72V e-rickshaw packs','E-Rickshaw Batteries',2)
) as v(name, slug, description, parent_name, sort_order)
join public.categories parent on parent.name = v.parent_name and parent.parent_id is null
on conflict (slug) do update
  set name        = excluded.name,
      description = excluded.description,
      parent_id   = excluded.parent_id,
      sort_order  = excluded.sort_order,
      is_active   = true;

-- ---------------------------------------------------------------------------
-- 2. Product pricing, stock, warranty, features, specifications, SEO
-- ---------------------------------------------------------------------------
update public.products p
   set price             = v.price,
       mrp               = v.mrp,
       compare_price     = v.mrp,
       stock             = v.stock,
       availability      = 'in_stock',
       warranty          = v.warranty,
       features          = v.features::jsonb,
       specifications    = v.specifications::jsonb,
       short_description = v.short_description,
       meta_title        = v.meta_title,
       meta_description  = v.meta_description,
       sort_order        = v.sort_order,
       is_active         = true,
       subcategory_id    = sub.id
from (values
  ('PR-001', 180000, 212500, 25, '2 Years Comprehensive Warranty', '["Pure sine wave output", "Built-in MPPT solar charge controller", "Seamless grid / solar / battery switching", "LCD and app monitoring", "Overload and short-circuit protection"]', '{"Rated Power": "3.6 kW", "Output Waveform": "Pure Sine Wave", "System Voltage": "48 V DC", "Solar Charge Controller": "MPPT", "Max PV Input": "4.7 kW", "Output Voltage": "230 V AC, 50 Hz", "Efficiency": "Up to 97%", "Communication": "Wi-Fi / RS485"}', 'Residential Hybrid Inverters', 'Grid-interactive hybrid inverter with built-in MPPT for homes and businesses.', 'PR Hybrid Inverter 3.6kW | PowerRun Industries', 'Buy PR Hybrid Inverter 3.6kW from PowerRun Industries. Grid-interactive hybrid inverter with built-in MPPT for homes and businesses. 2 Years Comprehensive Warranty. Pan-India delivery.', 1),
  ('PR-002', 200000, 236000, 25, '2 Years Comprehensive Warranty', '["Pure sine wave output", "Built-in MPPT solar charge controller", "Seamless grid / solar / battery switching", "LCD and app monitoring", "Overload and short-circuit protection"]', '{"Rated Power": "4.2 kW", "Output Waveform": "Pure Sine Wave", "System Voltage": "48 V DC", "Solar Charge Controller": "MPPT", "Max PV Input": "5.5 kW", "Output Voltage": "230 V AC, 50 Hz", "Efficiency": "Up to 97%", "Communication": "Wi-Fi / RS485"}', 'Residential Hybrid Inverters', 'Grid-interactive hybrid inverter with built-in MPPT for homes and businesses.', 'PR Hybrid Inverter 4.2kW | PowerRun Industries', 'Buy PR Hybrid Inverter 4.2kW from PowerRun Industries. Grid-interactive hybrid inverter with built-in MPPT for homes and businesses. 2 Years Comprehensive Warranty. Pan-India delivery.', 2),
  ('PR-003', 250000, 295000, 25, '2 Years Comprehensive Warranty', '["Pure sine wave output", "Built-in MPPT solar charge controller", "Seamless grid / solar / battery switching", "LCD and app monitoring", "Overload and short-circuit protection"]', '{"Rated Power": "6.2 kW", "Output Waveform": "Pure Sine Wave", "System Voltage": "48 V DC", "Solar Charge Controller": "MPPT", "Max PV Input": "8.1 kW", "Output Voltage": "230 V AC, 50 Hz", "Efficiency": "Up to 97%", "Communication": "Wi-Fi / RS485"}', 'Residential Hybrid Inverters', 'Grid-interactive hybrid inverter with built-in MPPT for homes and businesses.', 'PR Hybrid Inverter 6.2kW | PowerRun Industries', 'Buy PR Hybrid Inverter 6.2kW from PowerRun Industries. Grid-interactive hybrid inverter with built-in MPPT for homes and businesses. 2 Years Comprehensive Warranty. Pan-India delivery.', 3),
  ('PR-004', 280000, 330500, 25, '2 Years Comprehensive Warranty', '["Pure sine wave output", "Built-in MPPT solar charge controller", "Seamless grid / solar / battery switching", "LCD and app monitoring", "Overload and short-circuit protection"]', '{"Rated Power": "8.2 kW", "Output Waveform": "Pure Sine Wave", "System Voltage": "48 V DC", "Solar Charge Controller": "MPPT", "Max PV Input": "10.7 kW", "Output Voltage": "230 V AC, 50 Hz", "Efficiency": "Up to 97%", "Communication": "Wi-Fi / RS485"}', 'Commercial Hybrid Inverters', 'Grid-interactive hybrid inverter with built-in MPPT for homes and businesses.', 'PR Hybrid Inverter 8.2kW | PowerRun Industries', 'Buy PR Hybrid Inverter 8.2kW from PowerRun Industries. Grid-interactive hybrid inverter with built-in MPPT for homes and businesses. 2 Years Comprehensive Warranty. Pan-India delivery.', 4),
  ('PR-005', 320000, 377500, 25, '2 Years Comprehensive Warranty', '["Pure sine wave output", "Built-in MPPT solar charge controller", "Seamless grid / solar / battery switching", "LCD and app monitoring", "Overload and short-circuit protection"]', '{"Rated Power": "10.2 kW", "Output Waveform": "Pure Sine Wave", "System Voltage": "48 V DC", "Solar Charge Controller": "MPPT", "Max PV Input": "13.3 kW", "Output Voltage": "230 V AC, 50 Hz", "Efficiency": "Up to 97%", "Communication": "Wi-Fi / RS485"}', 'Commercial Hybrid Inverters', 'Grid-interactive hybrid inverter with built-in MPPT for homes and businesses.', 'PR Hybrid Inverter 10.2kW | PowerRun Industries', 'Buy PR Hybrid Inverter 10.2kW from PowerRun Industries. Grid-interactive hybrid inverter with built-in MPPT for homes and businesses. 2 Years Comprehensive Warranty. Pan-India delivery.', 5),
  ('PR-006', 350000, 413000, 25, '2 Years Comprehensive Warranty', '["Pure sine wave output", "Built-in MPPT solar charge controller", "Seamless grid / solar / battery switching", "LCD and app monitoring", "Overload and short-circuit protection"]', '{"Rated Power": "12.0 kW", "Output Waveform": "Pure Sine Wave", "System Voltage": "48 V DC", "Solar Charge Controller": "MPPT", "Max PV Input": "15.6 kW", "Output Voltage": "230 V AC, 50 Hz", "Efficiency": "Up to 97%", "Communication": "Wi-Fi / RS485"}', 'Commercial Hybrid Inverters', 'Grid-interactive hybrid inverter with built-in MPPT for homes and businesses.', 'PR Hybrid Inverter 12kW | PowerRun Industries', 'Buy PR Hybrid Inverter 12kW from PowerRun Industries. Grid-interactive hybrid inverter with built-in MPPT for homes and businesses. 2 Years Comprehensive Warranty. Pan-India delivery.', 6),
  ('PR-007', 120000, 141500, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "25.6 V", "Capacity": "100 Ah", "Energy": "2.56 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '24V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 25.6V 100Ah | PowerRun Industries', 'Buy PR LFP Battery 25.6V 100Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 7),
  ('PR-008', 180000, 212500, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "25.6 V", "Capacity": "200 Ah", "Energy": "5.12 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '24V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 25.6V 200Ah | PowerRun Industries', 'Buy PR LFP Battery 25.6V 200Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 8),
  ('PR-009', 220000, 259500, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "25.6 V", "Capacity": "280 Ah", "Energy": "7.17 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '24V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 25.6V 280Ah | PowerRun Industries', 'Buy PR LFP Battery 25.6V 280Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 9),
  ('PR-010', 280000, 330500, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "25.6 V", "Capacity": "550 Ah", "Energy": "14.08 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '24V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 25.6V 550Ah | PowerRun Industries', 'Buy PR LFP Battery 25.6V 550Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 10),
  ('PR-011', 150000, 177000, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "51.2 V", "Capacity": "100 Ah", "Energy": "5.12 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '48V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 51.2V 100Ah | PowerRun Industries', 'Buy PR LFP Battery 51.2V 100Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 11),
  ('PR-012', 200000, 236000, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "51.2 V", "Capacity": "200 Ah", "Energy": "10.24 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '48V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 51.2V 200Ah | PowerRun Industries', 'Buy PR LFP Battery 51.2V 200Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 12),
  ('PR-013', 250000, 295000, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "51.2 V", "Capacity": "280 Ah", "Energy": "14.34 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '48V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 51.2V 280Ah | PowerRun Industries', 'Buy PR LFP Battery 51.2V 280Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 13),
  ('PR-014', 320000, 377500, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "51.2 V", "Capacity": "400 Ah", "Energy": "20.48 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '48V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 51.2V 400Ah | PowerRun Industries', 'Buy PR LFP Battery 51.2V 400Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 14),
  ('PR-015', 400000, 472000, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "51.2 V", "Capacity": "600 Ah", "Energy": "30.72 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '48V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 51.2V 600Ah | PowerRun Industries', 'Buy PR LFP Battery 51.2V 600Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 15),
  ('PR-016', 500000, 590000, 25, '5 Years Warranty', '["LiFePO4 (LFP) cell chemistry", "Integrated Smart BMS", "6000+ cycle life", "Bluetooth / RS485 monitoring", "Deep discharge and over-charge protection"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "51.2 V", "Capacity": "800 Ah", "Energy": "40.96 kWh", "Cycle Life": "6000+ cycles at 80% DoD", "BMS": "Integrated Smart BMS", "Operating Temperature": "-10 C to 55 C", "Protection": "Over-charge / over-discharge / short circuit"}', '48V LFP Batteries', 'LiFePO4 energy storage with integrated smart BMS and long cycle life.', 'PR LFP Battery 51.2V 800Ah | PowerRun Industries', 'Buy PR LFP Battery 51.2V 800Ah from PowerRun Industries. LiFePO4 energy storage with integrated smart BMS and long cycle life. 5 Years Warranty. Pan-India delivery.', 16),
  ('PR-017', 35000, 41500, 25, '10 Years Product / 25 Years Performance Warranty', '["High-efficiency mono PERC cells", "Anti-PID and salt-mist resistant", "Tempered anti-reflective glass", "Withstands 2400 Pa wind load", "Optimised low-light performance"]', '{"Peak Power": "450 Wp", "Cell Type": "Mono PERC", "Module Efficiency": "Up to 21.3%", "Max System Voltage": "1500 V DC", "Frame": "Anodised aluminium alloy", "Glass": "3.2 mm tempered AR coated", "Operating Temperature": "-40 C to 85 C"}', 'Mono PERC Panels', 'High-efficiency mono PERC solar module for rooftop and ground-mount systems.', 'PR Solar Panel 450W | PowerRun Industries', 'Buy PR Solar Panel 450W from PowerRun Industries. High-efficiency mono PERC solar module for rooftop and ground-mount systems. 10 Years Product / 25 Years Performance Warranty. Pan-India delivery.', 17),
  ('PR-018', 45000, 53000, 25, '10 Years Product / 25 Years Performance Warranty', '["High-efficiency mono PERC cells", "Anti-PID and salt-mist resistant", "Tempered anti-reflective glass", "Withstands 2400 Pa wind load", "Optimised low-light performance"]', '{"Peak Power": "535 Wp", "Cell Type": "Mono PERC", "Module Efficiency": "Up to 21.3%", "Max System Voltage": "1500 V DC", "Frame": "Anodised aluminium alloy", "Glass": "3.2 mm tempered AR coated", "Operating Temperature": "-40 C to 85 C"}', 'Mono PERC Panels', 'High-efficiency mono PERC solar module for rooftop and ground-mount systems.', 'PR Solar Panel 535W | PowerRun Industries', 'Buy PR Solar Panel 535W from PowerRun Industries. High-efficiency mono PERC solar module for rooftop and ground-mount systems. 10 Years Product / 25 Years Performance Warranty. Pan-India delivery.', 18),
  ('PR-019', 50000, 59000, 25, '10 Years Product / 25 Years Performance Warranty', '["High-efficiency mono PERC cells", "Anti-PID and salt-mist resistant", "Tempered anti-reflective glass", "Withstands 2400 Pa wind load", "Optimised low-light performance"]', '{"Peak Power": "550 Wp", "Cell Type": "Mono PERC", "Module Efficiency": "Up to 21.3%", "Max System Voltage": "1500 V DC", "Frame": "Anodised aluminium alloy", "Glass": "3.2 mm tempered AR coated", "Operating Temperature": "-40 C to 85 C"}', 'Mono PERC Panels', 'High-efficiency mono PERC solar module for rooftop and ground-mount systems.', 'PR Solar Panel 550W | PowerRun Industries', 'Buy PR Solar Panel 550W from PowerRun Industries. High-efficiency mono PERC solar module for rooftop and ground-mount systems. 10 Years Product / 25 Years Performance Warranty. Pan-India delivery.', 19),
  ('PR-020', 55000, 65000, 25, '10 Years Product / 25 Years Performance Warranty', '["High-efficiency mono PERC cells", "Anti-PID and salt-mist resistant", "Tempered anti-reflective glass", "Withstands 2400 Pa wind load", "Optimised low-light performance"]', '{"Peak Power": "580 Wp", "Cell Type": "Mono PERC", "Module Efficiency": "Up to 21.3%", "Max System Voltage": "1500 V DC", "Frame": "Anodised aluminium alloy", "Glass": "3.2 mm tempered AR coated", "Operating Temperature": "-40 C to 85 C"}', 'Bifacial Panels', 'High-efficiency mono PERC solar module for rooftop and ground-mount systems.', 'PR Solar Panel 580W | PowerRun Industries', 'Buy PR Solar Panel 580W from PowerRun Industries. High-efficiency mono PERC solar module for rooftop and ground-mount systems. 10 Years Product / 25 Years Performance Warranty. Pan-India delivery.', 20),
  ('PR-021', 60000, 71000, 25, '10 Years Product / 25 Years Performance Warranty', '["High-efficiency mono PERC cells", "Anti-PID and salt-mist resistant", "Tempered anti-reflective glass", "Withstands 2400 Pa wind load", "Optimised low-light performance"]', '{"Peak Power": "600 Wp", "Cell Type": "Mono PERC", "Module Efficiency": "Up to 21.3%", "Max System Voltage": "1500 V DC", "Frame": "Anodised aluminium alloy", "Glass": "3.2 mm tempered AR coated", "Operating Temperature": "-40 C to 85 C"}', 'Bifacial Panels', 'High-efficiency mono PERC solar module for rooftop and ground-mount systems.', 'PR Solar Panel 600W | PowerRun Industries', 'Buy PR Solar Panel 600W from PowerRun Industries. High-efficiency mono PERC solar module for rooftop and ground-mount systems. 10 Years Product / 25 Years Performance Warranty. Pan-India delivery.', 21),
  ('PR-022', 95000, 112000, 25, '18 Months Warranty', '["Designed for daily deep cycling", "Vibration-resistant enclosure", "Fast charge capable", "Integrated BMS protection", "Maintenance free"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "48 V", "Capacity": "100 Ah", "Energy": "4.8 kWh", "Cycle Life": "3000+ cycles", "Application": "E-Rickshaw / E-Loader", "BMS": "Integrated with charge balancing"}', '48V E-Rickshaw Batteries', 'Deep-cycle lithium battery pack engineered for daily e-rickshaw duty.', 'PR E-Rickshaw Battery 48V 100Ah | PowerRun Industries', 'Buy PR E-Rickshaw Battery 48V 100Ah from PowerRun Industries. Deep-cycle lithium battery pack engineered for daily e-rickshaw duty. 18 Months Warranty. Pan-India delivery.', 22),
  ('PR-023', 110000, 130000, 25, '18 Months Warranty', '["Designed for daily deep cycling", "Vibration-resistant enclosure", "Fast charge capable", "Integrated BMS protection", "Maintenance free"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "2 V", "Capacity": "100 Ah", "Energy": "0.2 kWh", "Cycle Life": "3000+ cycles", "Application": "E-Rickshaw / E-Loader", "BMS": "Integrated with charge balancing"}', '48V E-Rickshaw Batteries', 'Deep-cycle lithium battery pack engineered for daily e-rickshaw duty.', 'PR E-Rickshaw Battery 51.2V 100Ah | PowerRun Industries', 'Buy PR E-Rickshaw Battery 51.2V 100Ah from PowerRun Industries. Deep-cycle lithium battery pack engineered for daily e-rickshaw duty. 18 Months Warranty. Pan-India delivery.', 23),
  ('PR-024', 125000, 147500, 25, '18 Months Warranty', '["Designed for daily deep cycling", "Vibration-resistant enclosure", "Fast charge capable", "Integrated BMS protection", "Maintenance free"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "72 V", "Capacity": "100 Ah", "Energy": "7.2 kWh", "Cycle Life": "3000+ cycles", "Application": "E-Rickshaw / E-Loader", "BMS": "Integrated with charge balancing"}', '72V E-Rickshaw Batteries', 'Deep-cycle lithium battery pack engineered for daily e-rickshaw duty.', 'PR E-Rickshaw Battery 72V 100Ah | PowerRun Industries', 'Buy PR E-Rickshaw Battery 72V 100Ah from PowerRun Industries. Deep-cycle lithium battery pack engineered for daily e-rickshaw duty. 18 Months Warranty. Pan-India delivery.', 24),
  ('PR-025', 140000, 165000, 25, '18 Months Warranty', '["Designed for daily deep cycling", "Vibration-resistant enclosure", "Fast charge capable", "Integrated BMS protection", "Maintenance free"]', '{"Chemistry": "LiFePO4", "Nominal Voltage": "72 V", "Capacity": "150 Ah", "Energy": "10.8 kWh", "Cycle Life": "3000+ cycles", "Application": "E-Rickshaw / E-Loader", "BMS": "Integrated with charge balancing"}', '72V E-Rickshaw Batteries', 'Deep-cycle lithium battery pack engineered for daily e-rickshaw duty.', 'PR E-Rickshaw Battery 72V 150Ah | PowerRun Industries', 'Buy PR E-Rickshaw Battery 72V 150Ah from PowerRun Industries. Deep-cycle lithium battery pack engineered for daily e-rickshaw duty. 18 Months Warranty. Pan-India delivery.', 25)
) as v(sku, price, mrp, stock, warranty, features, specifications,
       subcategory_name, short_description, meta_title, meta_description, sort_order)
left join public.categories sub
       on sub.name = v.subcategory_name and sub.parent_id is not null
where p.sku = v.sku;

-- ---------------------------------------------------------------------------
-- 3. Backfill anything the seed did not cover
-- ---------------------------------------------------------------------------
update public.products
   set availability = case when coalesce(stock, 0) > 0 then 'in_stock' else 'out_of_stock' end
 where availability is null;

update public.products
   set slug = lower(regexp_replace(trim(name), '[^a-zA-Z0-9]+', '-', 'g'))
 where slug is null or trim(slug) = '';

update public.products
   set meta_title = name || ' | PowerRun Industries'
 where meta_title is null;
